#!/usr/bin/perl

$input_file = "order.txt";
$output_file = "index.tex";

open INPUT, "<".$input_file or die "Could not open $input_file";
open OUTPUT, ">".$output_file or die "Cound not open $output_file for writing";

print OUTPUT "%Autogenerated from $input_file --- do not modify\n";

while(<INPUT>){
    chop;
    print OUTPUT "\\input\{$_.lagda\}\n";
}

close OUTPUT;
close INPUT;
